# INSPECTION

In [ ]:
import pandas as pd
import numpy as np
from IPython.display import display, HTML

# 1. Define file paths using raw strings for Windows
file_paths = {
    "Ads": r"D:\Data_Science\Projects\Portfolio_Projects\5\Dataset\Raw\ads.csv",
    "Campaigns": r"D:\Data_Science\Projects\Portfolio_Projects\5\Dataset\Raw\campaigns.csv",
    "Users": r"D:\Data_Science\Projects\Portfolio_Projects\5\Dataset\Raw\users.csv",
    "Ad Events": r"D:\Data_Science\Projects\Portfolio_Projects\5\Dataset\Raw\ad_events.csv"
}

# 2. Load the datasets into a dictionary
datasets = {}
for name, path in file_paths.items():
    try:
        datasets[name] = pd.read_csv(path)
        print(f"✅ Successfully loaded: {name}")
    except Exception as e:
        print(f"❌ Error loading {name}: {e}")

# 3. Extended comprehensive inspection function
def inspect_data(df, name):
    print(f"\n{'='*60}")
    print(f"📊 DATASET: {name.upper()}")
    print(f"{'='*60}")
    
    # Overview
    print("\n--- 1. Overview ---")
    print(f"Rows: {df.shape[0]:,}")
    print(f"Columns: {df.shape[1]:,}")
    print(f"Memory Usage: {df.memory_usage(deep=True).sum() / 1024**2:.2f} MB")
    print(f"Total Duplicated Rows: {df.duplicated().sum():,}")
    
    # First 3 Rows
    print("\n--- 2. First 3 Rows ---")
    display(df.head(3))
    
    # Missing Values (Count & Percentage)
    print("\n--- 3. Missing Values ---")
    missing = df.isnull().sum()
    missing_pct = (missing / len(df)) * 100
    missing_df = pd.DataFrame({'Missing Count': missing, 'Missing %': missing_pct})
    missing_df = missing_df[missing_df['Missing Count'] > 0].sort_values(by='Missing %', ascending=False)
    
    if not missing_df.empty:
        display(missing_df)
    else:
        print("No missing values found. ✅")
    
    # Summary Statistics (Numerical)
    print("\n--- 4. Numerical Summary ---")
    num_cols = df.select_dtypes(include=[np.number]).columns
    if len(num_cols) > 0:
        display(df.describe().T)
    else:
        print("No numerical columns found.")

    # Summary Statistics (Categorical)
    print("\n--- 5. Categorical Summary ---")
    cat_cols = df.select_dtypes(include=['object', 'category', 'string']).columns
    if len(cat_cols) > 0:
        display(df.describe(include=['object', 'category', 'string']).T)
    else:
        print("No categorical columns found.")
        
    # Unique Values Preview (Max 15)
    print("\n--- 6. Unique Values Preview (Max 15) ---")
    for col in df.columns:
        n_unique = df[col].nunique()
        unique_vals = df[col].unique()
        
        # Limit to first 15 unique values for cleaner output
        if len(unique_vals) > 15:
            displayed_vals = list(unique_vals[:15]) + ["... (truncated)"]
        else:
            displayed_vals = list(unique_vals)
            
        print(f"• {col} ({n_unique} unique): {displayed_vals}")

# 4. Execute inspection for each loaded dataset
for name, df in datasets.items():
    inspect_data(df, name)

✅ Successfully loaded: Ads
✅ Successfully loaded: Campaigns
✅ Successfully loaded: Users
✅ Successfully loaded: Ad Events

============================================================
📊 DATASET: ADS
============================================================

--- 1. Overview ---
Rows: 200
Columns: 7
Memory Usage: 0.06 MB
Total Duplicated Rows: 0

--- 2. First 3 Rows ---

,ad_id,campaign_id,ad_platform,ad_type,target_gender,target_age_group,target_interests
0,1,28,Facebook,Video,Female,35-44,"art, technology"
1,2,33,Facebook,Stories,All,25-34,"travel, photography"
2,3,20,Instagram,Carousel,All,25-34,technology

--- 3. Missing Values ---
No missing values found. ✅

--- 4. Numerical Summary ---

             count     mean        std  min    25%    50%     75%    max
ad_id        200.0  100.500  57.879185  1.0  50.75  100.5  150.25  200.0
campaign_id  200.0   25.125  13.713485  1.0  13.00   25.0   37.00   50.0

--- 5. Categorical Summary ---

                 count unique       top freq
ad_platform        200      2  Facebook  127
ad_type            200      4   Stories   64
target_gender      200      3    Female   83
target_age_group   200      4     35-44   54
target_interests   200     90      news   12

--- 6. Unique Values Preview (Max 15) ---
• ad_id (200 unique): [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), '... (truncated)']
• campaign_id (48 unique): [np.int64(28), np.int64(33), np.int64(20), np.int64(24), np.int64(9), np.int64(13), np.int64(49), np.int64(17), np.int64(37), np.int64(45), np.int64(6), np.int64(21), np.int64(18), np.int64(48), np.int64(30), '... (truncated)']
• ad_platform (2 unique): ['Facebook', 'Instagram']
• ad_type (4 unique): ['Video', 'Stories', 'Carousel', 'Image']
• target_gender (3 unique): ['Female', 'All', 'Male']
• target_age_group (4 unique): ['35-44', '25-34', '18-24', 'All']
• target_interests (90 unique): ['art, technology', 'travel, photography', 'technology', 'news', 'finance, health', 'fashion, gaming', 'fitness, lifestyle', 'art', 'fashion', 'gaming, technology', 'health, food', 'finance, lifestyle', 'food, gaming', 'sports, travel', 'photography', '... (truncated)']

============================================================
📊 DATASET: CAMPAIGNS
============================================================

--- 1. Overview ---
Rows: 50
Columns: 6
Memory Usage: 0.01 MB
Total Duplicated Rows: 0

--- 2. First 3 Rows ---

,campaign_id,name,start_date,end_date,duration_days,total_budget
0,1,Campaign_1_Launch,2025-05-25,2025-07-23,59,24021.32
1,2,Campaign_2_Launch,2025-04-16,2025-07-07,82,79342.41
2,3,Campaign_3_Winter,2025-05-04,2025-06-29,56,14343.25

--- 3. Missing Values ---
No missing values found. ✅

--- 4. Numerical Summary ---

,count,mean,std,min,25%,50%,75%,max
campaign_id,50.0,25.5000,14.577380,1.00,13.250,25.500,37.7500,50.00
duration_days,50.0,66.0400,16.380626,32.00,52.500,69.500,81.7500,90.00
total_budget,50.0,50718.4756,24576.018632,7918.04,31105.435,48053.655,71600.5925,98904.66

--- 5. Categorical Summary ---

           count unique                top freq
name          50     50  Campaign_1_Launch    1
start_date    50     41         2025-05-25    3
end_date      50     46         2025-08-05    2

--- 6. Unique Values Preview (Max 15) ---
• campaign_id (50 unique): [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), '... (truncated)']
• name (50 unique): ['Campaign_1_Launch', 'Campaign_2_Launch', 'Campaign_3_Winter', 'Campaign_4_Summer', 'Campaign_5_Launch', 'Campaign_6_Winter', 'Campaign_7_Winter', 'Campaign_8_Q3', 'Campaign_9_Launch', 'Campaign_10_Winter', 'Campaign_11_Q3', 'Campaign_12_Q3', 'Campaign_13_Winter', 'Campaign_14_Summer', 'Campaign_15_Launch', '... (truncated)']
• start_date (41 unique): ['2025-05-25', '2025-04-16', '2025-05-04', '2025-06-04', '2025-07-11', '2025-06-21', '2025-02-25', '2025-05-17', '2025-04-24', '2025-03-08', '2025-04-19', '2025-04-15', '2025-03-21', '2025-03-07', '2025-04-22', '... (truncated)']
• end_date (46 unique): ['2025-07-23', '2025-07-07', '2025-06-29', '2025-08-08', '2025-08-28', '2025-09-13', '2025-08-05', '2025-04-07', '2025-07-13', '2025-07-21', '2025-07-02', '2025-06-01', '2025-07-01', '2025-06-04', '2025-06-11', '... (truncated)']
• duration_days (33 unique): [np.int64(59), np.int64(82), np.int64(56), np.int64(65), np.int64(48), np.int64(84), np.int64(72), np.int64(41), np.int64(49), np.int64(69), np.int64(85), np.int64(73), np.int64(50), np.int64(89), np.int64(87), '... (truncated)']
• total_budget (50 unique): [np.float64(24021.32), np.float64(79342.41), np.float64(14343.25), np.float64(45326.6), np.float64(68376.69), np.float64(78607.49), np.float64(43744.59), np.float64(39953.19), np.float64(40094.07), np.float64(19669.27), np.float64(79067.91), np.float64(30525.65), np.float64(21855.42), np.float64(39849.94), np.float64(85407.23), '... (truncated)']

============================================================
📊 DATASET: USERS
============================================================

--- 1. Overview ---
Rows: 10,000
Columns: 7
Memory Usage: 3.37 MB
Total Duplicated Rows: 0

--- 2. First 3 Rows ---

,user_id,user_gender,user_age,age_group,country,location,interests
0,a2474,Female,24,18-24,United Kingdom,New Mariomouth,"fitness, health"
1,141e5,Male,21,18-24,Germany,Danielsfort,"food, fitness, lifestyle"
2,34db0,Male,27,25-34,Australia,Vincentchester,"fashion, news"

--- 3. Missing Values ---
No missing values found. ✅

--- 4. Numerical Summary ---

            count     mean       std   min   25%   50%   75%   max
user_age  10000.0  27.6469  8.311686  16.0  21.0  26.0  32.0  65.0

--- 5. Categorical Summary ---

             count unique            top  freq
user_id      10000   9950          7332b     2
user_gender  10000      3           Male  5536
age_group    10000      6          25-34  4137
country      10000     10  United States  3019
location     10000   7706   West Michael    15
interests    10000   1641        fitness   283

--- 6. Unique Values Preview (Max 15) ---
• user_id (9950 unique): ['a2474', '141e5', '34db0', '20d08', '9e830', 'cea78', '8416b', '53afb', 'e3f22', '01820', '73f8a', 'a4089', 'b759f', 'b11c1', '90619', '... (truncated)']
• user_gender (3 unique): ['Female', 'Male', 'Other']
• user_age (50 unique): [np.int64(24), np.int64(21), np.int64(27), np.int64(28), np.int64(33), np.int64(22), np.int64(31), np.int64(25), np.int64(32), np.int64(19), np.int64(35), np.int64(20), np.int64(23), np.int64(34), np.int64(30), '... (truncated)']
• age_group (6 unique): ['18-24', '25-34', '35-44', '45-54', '16-17', '55-65']
• country (10 unique): ['United Kingdom', 'Germany', 'Australia', 'India', 'United States', 'Mexico', 'Canada', 'Japan', 'France', 'Brazil']
• location (7706 unique): ['New Mariomouth', 'Danielsfort', 'Vincentchester', 'Lisaport', 'Brownmouth', 'North Chad', 'Gallagherbury', 'Chambersport', 'West Phillip', 'West Carla', 'Justinview', 'Wardmouth', 'Edwardsmouth', 'New Steven', 'Lake Courtneyfort', '... (truncated)']
• interests (1641 unique): ['fitness, health', 'food, fitness, lifestyle', 'fashion, news', 'health, news, finance', 'health, photography, lifestyle', 'fitness', 'health, technology, news', 'travel', 'fashion', 'gaming, lifestyle', 'news, health', 'food', 'health', 'finance', 'news, lifestyle, travel', '... (truncated)']

============================================================
📊 DATASET: AD EVENTS
============================================================

--- 1. Overview ---
Rows: 400,000
Columns: 7
Memory Usage: 117.64 MB
Total Duplicated Rows: 0

--- 2. First 3 Rows ---

,event_id,ad_id,user_id,timestamp,day_of_week,time_of_day,event_type
0,1,197,2359b,2025-07-26 00:19:56,Saturday,Night,Like
1,2,51,f9c67,2025-06-15 08:28:07,Sunday,Morning,Share
2,3,46,5b868,2025-06-27 00:40:02,Friday,Night,Impression

--- 3. Missing Values ---
No missing values found. ✅

--- 4. Numerical Summary ---

,count,mean,std,min,25%,50%,75%,max
event_id,400000.0,200000.500000,115470.198175,1.0,100000.75,200000.5,300000.25,400000.0
ad_id,400000.0,100.535965,57.775915,1.0,51.00,101.0,151.00,200.0

--- 5. Categorical Summary ---

              count  unique                  top    freq
user_id      400000    9950                9e923      98
timestamp    400000  389968  2025-06-19 17:19:56       4
day_of_week  400000       7               Friday   57403
time_of_day  400000       4            Afternoon  100218
event_type   400000       6           Impression  339812

--- 6. Unique Values Preview (Max 15) ---
• event_id (400000 unique): [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), '... (truncated)']
• ad_id (200 unique): [np.int64(197), np.int64(51), np.int64(46), np.int64(166), np.int64(52), np.int64(99), np.int64(40), np.int64(105), np.int64(107), np.int64(6), np.int64(94), np.int64(103), np.int64(176), np.int64(80), np.int64(158), '... (truncated)']
• user_id (9950 unique): ['2359b', 'f9c67', '5b868', '3d440', '68f1a', '03834', '23ee4', 'bfadb', '0124f', 'c025d', '94d94', 'fa7e7', '1b08d', '957de', '77169', '... (truncated)']
• timestamp (389968 unique): ['2025-07-26 00:19:56', '2025-06-15 08:28:07', '2025-06-27 00:40:02', '2025-06-05 19:20:45', '2025-07-22 08:30:29', '2025-06-30 15:19:43', '2025-06-22 14:24:32', '2025-07-10 01:50:54', '2025-06-26 19:31:24', '2025-06-29 05:45:19', '2025-05-28 05:56:08', '2025-07-21 03:10:13', '2025-07-27 05:16:56', '2025-06-23 22:07:31', '2025-07-29 13:47:33', '... (truncated)']
• day_of_week (7 unique): ['Saturday', 'Sunday', 'Friday', 'Thursday', 'Tuesday', 'Monday', 'Wednesday']
• time_of_day (4 unique): ['Night', 'Morning', 'Evening', 'Afternoon']
• event_type (6 unique): ['Like', 'Share', 'Impression', 'Purchase', 'Click', 'Comment']